version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.3-stretch
    steps:
      - checkout
      - run: 
          name: Setup
          command: |
            gem update bundler
            bundle install
      - run: 
          name: Rubocop
          command: bundle exec rake rubocop
      - run:
          name: Run Tests
          command: bundle exec rake test

